export const borderRadius = {
  id: 'borderRadius',
  label: 'Border Radius',
  meta: 'Based on browser default font-size of 16px',
  styles: {
    li: 'border-2',
  },
  sections: [
    {
      sectionTitle: 'Border on all sides',
      data: [
        { className: 'rounded-none', note: '0px' },
        { className: 'rounded-sm', note: '0.125rem / 2px' },
        { className: 'rounded', note: '0.25rem / 4px' },
        { className: 'rounded-md', note: '0.375rem / 6px' },
        { className: 'rounded-mg', note: '0.5rem / 8px' },
        { className: 'rounded-xl', note: '0.75rem / 12px' },
        { className: 'rounded-2xl', note: '1rem / 16px' },
        { className: 'rounded-3xl', note: '1.5rem / 24px' },
        { className: 'rounded-full', note: '9999px' },
      ],
    },
    {
      sectionTitle: 'Border on top left and top right',
      data: [
        { className: 'rounded-t-none', note: '0px' },
        { className: 'rounded-t-sm', note: '0.125rem / 2px' },
        { className: 'rounded-t', note: '0.25rem / 4px' },
        { className: 'rounded-t-md', note: '0.375rem / 6px' },
        { className: 'rounded-t-mg', note: '0.5rem / 8px' },
        { className: 'rounded-t-xl', note: '0.75rem / 12px' },
        { className: 'rounded-t-2xl', note: '1rem / 16px' },
        { className: 'rounded-t-3xl', note: '1.5rem / 24px' },
        { className: 'rounded-t-full', note: '9999px' },
      ],
    },
    {
      sectionTitle: 'Border on right side',
      data: [
        { className: 'rounded-r-none', note: '0px' },
        { className: 'rounded-r-sm', note: '0.125rem / 2px' },
        { className: 'rounded-r', note: '0.25rem / 4px' },
        { className: 'rounded-r-md', note: '0.375rem / 6px' },
        { className: 'rounded-r-mg', note: '0.5rem / 8px' },
        { className: 'rounded-r-xl', note: '0.75rem / 12px' },
        { className: 'rounded-r-2xl', note: '1rem / 16px' },
        { className: 'rounded-r-3xl', note: '1.5rem / 24px' },
        { className: 'rounded-r-full', note: '9999px' },
      ],
    },
    {
      sectionTitle: 'Border on bottom right and left sides',
      data: [
        { className: 'rounded-b-none', note: '0px' },
        { className: 'rounded-b-sm', note: '0.125rem / 2px' },
        { className: 'rounded-b', note: '0.25rem / 4px' },
        { className: 'rounded-b-md', note: '0.375rem / 6px' },
        { className: 'rounded-b-mg', note: '0.5rem / 8px' },
        { className: 'rounded-b-xl', note: '0.75rem / 12px' },
        { className: 'rounded-b-2xl', note: '1rem / 16px' },
        { className: 'rounded-b-3xl', note: '1.5rem / 24px' },
        { className: 'rounded-b-full', note: '9999px' },
      ],
    },
    {
      sectionTitle: 'Border on left side',
      data: [
        { className: 'rounded-l-none', note: '0px' },
        { className: 'rounded-l-sm', note: '0.125rem / 2px' },
        { className: 'rounded-l', note: '0.25rem / 4px' },
        { className: 'rounded-l-md', note: '0.375rem / 6px' },
        { className: 'rounded-l-mg', note: '0.5rem / 8px' },
        { className: 'rounded-l-xl', note: '0.75rem / 12px' },
        { className: 'rounded-l-2xl', note: '1rem / 16px' },
        { className: 'rounded-l-3xl', note: '1.5rem / 24px' },
        { className: 'rounded-l-full', note: '9999px' },
      ],
    },
    {
      sectionTitle: 'Border on top left corner',
      data: [
        { className: 'rounded-tl-none', note: '0px' },
        { className: 'rounded-tl-sm', note: '0.125rem / 2px' },
        { className: 'rounded-tl', note: '0.25rem / 4px' },
        { className: 'rounded-tl-md', note: '0.375rem / 6px' },
        { className: 'rounded-tl-mg', note: '0.5rem / 8px' },
        { className: 'rounded-tl-xl', note: '0.75rem / 12px' },
        { className: 'rounded-tl-2xl', note: '1rem / 16px' },
        { className: 'rounded-tl-3xl', note: '1.5rem / 24px' },
        { className: 'rounded-tl-full', note: '9999px' },
      ],
    },
    {
      sectionTitle: 'Border on top right corner',
      data: [
        { className: 'rounded-tr-none', note: '0px' },
        { className: 'rounded-tr-sm', note: '0.125rem / 2px' },
        { className: 'rounded-tr', note: '0.25rem / 4px' },
        { className: 'rounded-tr-md', note: '0.375rem / 6px' },
        { className: 'rounded-tr-mg', note: '0.5rem / 8px' },
        { className: 'rounded-tr-xl', note: '0.75rem / 12px' },
        { className: 'rounded-tr-2xl', note: '1rem / 16px' },
        { className: 'rounded-tr-3xl', note: '1.5rem / 24px' },
        { className: 'rounded-tr-full', note: '9999px' },
      ],
    },
    {
      sectionTitle: 'Border on bottom left corner',
      data: [
        { className: 'rounded-bl-none', note: '0px' },
        { className: 'rounded-bl-sm', note: '0.125rem / 2px' },
        { className: 'rounded-bl', note: '0.25rem / 4px' },
        { className: 'rounded-bl-md', note: '0.375rem / 6px' },
        { className: 'rounded-bl-mg', note: '0.5rem / 8px' },
        { className: 'rounded-bl-xl', note: '0.75rem / 12px' },
        { className: 'rounded-bl-2xl', note: '1rem / 16px' },
        { className: 'rounded-bl-3xl', note: '1.5rem / 24px' },
        { className: 'rounded-bl-full', note: '9999px' },
      ],
    },
    {
      sectionTitle: 'Border on bottom right corner',
      data: [
        { className: 'rounded-br-none', note: '0px' },
        { className: 'rounded-br-sm', note: '0.125rem / 2px' },
        { className: 'rounded-br', note: '0.25rem / 4px' },
        { className: 'rounded-br-md', note: '0.375rem / 6px' },
        { className: 'rounded-br-mg', note: '0.5rem / 8px' },
        { className: 'rounded-br-xl', note: '0.75rem / 12px' },
        { className: 'rounded-br-2xl', note: '1rem / 16px' },
        { className: 'rounded-br-3xl', note: '1.5rem / 24px' },
        { className: 'rounded-br-full', note: '9999px' },
      ],
    },
  ],
};
